# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d5dc830a98ea6be209ca918e2c8fc5b066b4f264fcdb31760b8ab018431a3e3672b4492c9f448cfa911803d78fbae488d2ee310c5af4fc09c1f22924dc9ff93

test:
  secret_key_base: b2043455eba1e00f7dadd48763d2d34608a753ae513d2a218bb730b9413a1379662e2b3e72196ca8987f5cbc8056c0276d33afea5469e225cbd4616a26a2b842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
